### ISSUE TITLE
Error 'str' object has no attribute 'exists' on generate-tests with parameter --destination

### ISSUE THREAD

**Issue by tanzilkm** [ChristianBirchler/sdc-scissor#34]
When we run **generate-tests** commend to generate test case with parameter destination  we get error (_'str' object has no attribute 'exists'_ )

#### $ poetry run python sdc-scissor.py generate-tests --destination C:\Users\user\Documents\
`INFO:root:generate_tests
Traceback (most recent call last):
  File "..\sdc-scissor\sdc-scissor.py", line 132, in <module>
    cli()
  File "..\sdc-scissor\venv\lib\site-packages\click\core.py", line 1130, in __call__
    return self.main(*args, **kwargs)
  File "..\sdc-scissor\venv\lib\site-packages\click\core.py", line 1055, in main
    rv = self.invoke(ctx)
  File "..\sdc-scissor\venv\lib\site-packages\click\core.py", line 1657, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "..\sdc-scissor\venv\lib\site-packages\click\core.py", line 1404, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "..\sdc-scissor\venv\lib\site-packages\click\core.py", line 760, in invoke
    return __callback(*args, **kwargs)
  File "..\sdc-scissor\sdc-scissor.py", line 35, in generate_tests
    if not destination.exists():
AttributeError: 'str' object has no attribute 'exists'`

**Comment by tanzilkm** [comment]
The issue was fixed in following merge 54beb1537dcb47d9595c91794d7b1da90837dc87
