### ISSUE TITLE
ModuleNotFoundError: No module named 'pymoo.model'

### ISSUE THREAD

**Issue by RoboticistAbdulrahman** [ChristianBirchler/sdc-scissor#56]
i'm having an issue with the latest update 

(myenv) C:\Users\User\Desktop\sdc-scissor>    python3.9 sdc-scissor.py generate-tests
Traceback (most recent call last):
  File "C:\Users\User\Desktop\sdc-scissor\sdc-scissor.py", line 8, in <module>
    from sdc_scissor.testing_api.test_generator import TestGenerator
  File "C:\Users\User\Desktop\sdc-scissor\sdc_scissor\testing_api\test_generator.py", line 6, in <module>
    from sdc_scissor.testing_api.test_generators.ambiegen.ambiegen_generator import CustomAmbieGenGenerator
  File "C:\Users\User\Desktop\sdc-scissor\sdc_scissor\testing_api\test_generators\ambiegen\ambiegen_generator.py", line 7, in <module>
    from sdc_scissor.testing_api.test_generators.ambiegen.Utils.test_case_problem import TestCaseProblem
  File "C:\Users\User\Desktop\sdc-scissor\sdc_scissor\testing_api\test_generators\ambiegen\Utils\test_case_problem.py", line 1, in <module>     
    from pymoo.model.problem import Problem
ModuleNotFoundError: No module named 'pymoo.model'

**Comment by RoboticistAbdulrahman** [comment]
Hi @ChristianBirchler, I'll close this issue for now as it was existed in the previous version v2.0, i'll do my tests on the latest version and keep you updated. 
Thanks you
